server:
  port: 9296

spring:
  application:
    name: configuration-management-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/chiranwettewa/Shopping-cart-app-configuration
logging:
  file:
    name: D:/logs/configuration-management-service.log